<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('24h du code')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/datatables/dataTables.bootstrap4.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.foundation.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.jqueryui.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.material.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.semanticui.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.uikit.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/jquery.dataTables_themeroller.css'))
            ->prependStylesheet($this->basePath('css/datatables/jquery.dataTables.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/datatables/jquery.dataTables.js'))
            //->prependFile('https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js')
            //->prependFile('https://code.jquery.com/jquery-1.12.4.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/datatables/jquery.js'))
            //->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.bootstrap.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.bootstrap4.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.foundation.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.jqueryui.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.material.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.semanticui.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.uikit.min.js'))
            
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:#1ba5ca;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo-blanc-1.png') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" style="margin-left:20px;width: 550px;margin:auto;">
                        <!--li><a href="<?= $this->url('home') ?>">Home</a></li-->
                        <li id="menu_partieencours"><a href="/partie/encours">Partie en cours</a>
                            <!--
                            <ul id="jq-espace_travail" class="nav nav-second-level nav-workspace-level">
                                <li><a href="<?= $this->url('album') ?>">Ajouter</a></li>
                            </ul>
                            -->
                        </li>
                        <li id="menu_listesparties"><a href="/partie/liste">Listes parties</a></li>
                        <li id="menu_nouvellepartie"><a href="/partie/nouvelle">Nouvelle partie</a>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <h1>Sopra - Jeux de flèchettes</h1>
<!--             Site tuto ZF3 : <a href="https://docs.zendframework.com/tutorials/getting-started/forms-and-actions/">https://docs.zendframework.com/tutorials/getting-started/forms-and-actions/</a><br>
            Menu : voir identique sur WTG<br> -->
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
