<?php
// module/Listes/view/listes/listes/index.phtml:

$title = 'Mes graphes';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?= $myJs ?>



<table class="table">
<!--     <tr>
        <td>Sources ayant permis la contruction de l'image HightGraph : <a href="https://packagist.org/packages/ghunti/highcharts-php">https://packagist.org/packages/ghunti/highcharts-php</a></td>
    </tr> -->
    <tr>
        <td>
            <table id="example" class="display" width="100%" cellspacing="0">
                
                <!--<div class="row">
                    <img src="<?php /*$graphique->Stroke()*/ ?>" />
                </div>-->
            </table>
        </td>
    </tr>

</table>

<div id="container" style="width:100%; height:400px;"></div>
<script type="text/javascript">
    <?= $myChart ?>
</script>
