<?php
// module/Listes/view/listes/listes/index.phtml:

$title = 'Partie '.$partie_statut;
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<!-- JS pour hightcharts --->
<script type="text/javascript" src="/js/highcharts.js"></script>
<script type="text/javascript" src="/js/highcharts-more.js">
</script><script type="text/javascript" src="/js/exporting.js"></script>


<script type="text/javascript">
var dataSet = [
    <?php foreach($tableau_resultat AS $value) { ?>
    [ "<?= $value['nom'] ?>", [<?= $value['1']['points'] ?>], [<?= $value['2']['points'] ?>], [<?= $value['3']['points'] ?>], [<?= $value['4']['points'] ?>], [<?= $value['5']['points'] ?>], [<?= $value['6']['points'] ?>], [<?= $value['7']['points'] ?>], [<?= $value['8']['points'] ?>], [<?= $value['9']['points'] ?>], [<?= $value['10']['points'] ?>]],
    <?php } ?>
];
 
$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet,
        "bFilter" : false,               
        "bLengthChange": false,
        "bInfo" : false,
        "bPaginate": false , 
        columns: [
            { title: "Nom" },
            { title: "1" },
            { title: "2" },
            { title: "3" },
            { title: "4" },
            { title: "5" },
            { title: "6" },
            { title: "7" },
            { title: "8" },
            { title: "9" },
            { title: "10" },
        ],
    } );
} );
</script>

<table class="table">
<!--
    <tr>
        <td>Sources ayant permis la contruction du tableau : <a href="https://datatables.net/examples/data_sources/ajax.html">https://datatables.net/examples/data_sources/ajax.html</a></td>
    </tr>
-->


    <tr id="bandeau">
        <td id="bandeau2">
            <input type="button" value="<?= $statutLancer ?>" id="activerlancer" class="btn btn-primary">
        </td>
    </tr>
    <tr>
        <td>
            <table id="example" class="display" width="100%" cellspacing="0">
               
            </table>
        </td>
    </tr>

</table>

<div id="container" style="width:100%; height:400px;"></div>
<div id="container2" style="width:100%; height:400px;"></div>

<script type="text/javascript">
    <?= $myChart ?>
        
    <?= $myChart2 ?>
    

        
    $(document).ready(function() {
        $("tr:even").css("background", "#ededed");
        $("th").css("background", "#454545");


        $("#example td").each(function() {
          var value = $(this).text();
            if (parseInt(value)) {
                var trois_lances = value.split(",");

                if (trois_lances.length>2) {
                    console.log('test');
                }

                trois_lances = eval(trois_lances.join("+"));
                html  ='<div class="c--anim-btn">';
                html +='  <span class="c-anim-btn">';
                html +=     trois_lances;
                html +='  </span>';
                html +='  <span>';
                html +=     value;
                html +='  </span>';
                html +='</div>';
                $(this).html(html);
            }
          
        });
    });


$(function(){
    $("#activerlancer").click(function(event){
        event.preventDefault();

        $.ajax({
            url: '/retournejson/activelancer/<?= $id_partie ?>',
            type: 'POST',
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            async: true,
            data: ($("#activerlancer").serialize()),
            success: function (data) {
                console.log(data);
                if(data.data.nouveauStatut == 0) {
                    $("#activerlancer").prop('value', 'Activer Lancer');
                }
                else {
                    $("#activerlancer").prop('value', 'Stopper Lancer');
                }
                return false;
            },
            error: function (data) {
                console.log(data.toSource());

            }
        });
    })
})

$("#menu_partieencours").addClass("active");
</script>